### ISSUE TITLE
User assignable vital info on space loadout screen

### ISSUE THREAD

**Issue by MaraMorrigan** [STOCD/SETS#10]
Ship name, faction, build type tags, and scrollable description box should be added.

**Comment by Liraal2** [comment]
Current UI does not provide space for desription box. Please specify location.

**Comment by nehpetsca** [comment]
Integrated Description above build tags / captain details (separate space and ground descriptions) and data to JSON store.
Minor compression of existing text for 3 lines -- this may not be enough in the long run (possible tabbed solution to swap stats panel with a full-sized description panel in future?)

Original list complete
