### ISSUE TITLE
Subsystem - Build Tags

### ISSUE THREAD

**Issue by MaraMorrigan** [STOCD/SETS#11]
Used to help with sorting in the community library and serve as a quick visual reference on the loadout screen, build tags should include, but not be limited to (cmon a girl is allowed to miss something)

Phaser/Disruptor/Plasma/Polaron/Antiproton/Tetryon

Exotic/Kinetic/DEW/Mine (prefix Hybrid is selectable + any of the others)

Cannon/Beam

Single Target/AoE

DPS/Tank/Support/Drain/Control

Off-Meta/Theme

**Comment by Shinga13** [comment]
Some tags are implemented (DEW, KINETIC, EPG, DEWSCI, THEME), bringing it to the structure above would be optimal:
Maybe with a visual Hierachy?:
1) Exotic /     Kinetic    /                                                DEW                                          / Hybrid
2)           | Mine / Torp |                                      Cannon / Beam                                    |
3)                                 | Phaser / Disruptor / Plasma / Polaron / Antiproton / Tetryon |

Outside of Hierachy:
Singe Target / AoE and Roles

**Comment by Shinga13** [comment]
Implemented, if other tags are needed, we can quite easily add them
