### ISSUE TITLE
Experimental Weapon and Secondary Deflector slots missing

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#12]
As the title says, I'm not able to find Experimental weapon slots on any ship.

**Comment by Liraal2** [comment]
Added secdef/exp weapon support in commit 579a7e4af2143575dfeb51c000f9b114074144b1.

**Comment by Shinga13** [comment]
After my testing with the 579a7e4 version SecDefs and ExpWeapons only show up sporadically (with alita and titan class being two of the few with a expweapon slot and titan the only one I could find a SecDef slot on)
