### ISSUE TITLE
Missing / Wrong Images Wrapper

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#22]
Comment below which images are missing. This is here to give an overview about which items wiki pages don't interact correctly with SETS.

**Comment by Shinga13** [comment]
B'rel Bird-of-Prey uses image from Breen Plesh Brek Heavy Raider;
Sol Deflector Array has no image;
Section 31 Heavy Battlecruiser ha no image;

**Comment by Shinga13** [comment]
Terran Task Force Torpedo Launcher has no image;
Improvised Boarding Party Personal Space Trait has no image;

**Comment by nehpetsca** [comment]
Is there a better place that these and the other wiki items can be kept in a one-issue-per-item checklist?  This is not really a very workable way of tracking the wide variety of minor items.  I can try to work them from here, but it will not be as fast and fixes will not be easy to mark/document.

**Comment by nehpetsca** [comment]
Terran task force torpedo: image currently loads ok
Improvised boarding party: image currently loads ok
B'rel Bird-of-Prey: image currently ok
Sol Deflector Array: Renamed to Sol Defense Deflector Array (matches icon name, but new name not yet showing in SETS)
Section 31 Heavy Battlecruiser: Image exists, JSON for SETS contains correct image name, accessible in web -- not sure why it's not loading.

**Comment by Shinga13** [comment]
You're absolutely right, this kind of thread for such a work is more that suboptimal

**Comment by Shinga13** [comment]
- [ ] test

**Comment by Shinga13** [comment]
- [ ] Surgical Strikes Intel boff ability missing image
- [ ] Transport Warhead Intel boff ability missing image
