### ISSUE TITLE
Infoboxes for traits and abilities

### ISSUE THREAD

**Issue by Liraal2** [STOCD/SETS#35]
Currently only ship equipment supports infoboxes. This needs to be extended to all build elements.

**Comment by Shinga13** [comment]
If you're working on infoboxes: They don't work with equipment loaded in from a json or png.

**Comment by nehpetsca** [comment]
infoboxes should work from a json now -- I'll check on png loading
Equipment, traits/shiptraits, BOFF skills all provide descriptions to the infobox now
Ships could use some form of basic description still, though DOFFs appear self-describing.

Skill tree hasn't been touched yet.
