### ISSUE TITLE
Infobox performance

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#59]
- [ ] Hovering too fast over too many items lets the Infobox including buttons flicker gray as well as the ship image glitch around (Fix could be a tooltip delay like ingame)
- [x] On some items (With a large infobox I believe) the infobox and import / export button flicker grey

**Comment by nehpetsca** [comment]
button bar separated to stop the flickering.
Several framing improvements -- may stop the ship image glitch

**Comment by Shinga13** [comment]
Infobox is completely new -- with new issues. See #62
