### ISSUE TITLE
Infobox performance # 2

### ISSUE THREAD

**Issue by Shinga13** [STOCD/SETS#68]
First displayed infobox on ground and space has a massive delay. 
Infoboxes for Equipment still load too slow. Sometimes they come up almost instantly, but that is not the rule. I believe that this is because of the additional code handling sub-line formatting, but I don't know how to improve it further.

**Comment by nehpetsca** [comment]
* Equipment added into precache group
* Precaching can no longer be disabled outright (will be developed into fast-start with safe options)

Tested on osx/linux/win

Please verify if you are still experiencing delays

**Comment by Shinga13** [comment]
still delays there, but everything below half a second so I guess it's ok
